# Generated by Django 5.0.14 on 2026-07-27 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('actor', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('CONTRIBUTION', 'Positive Contribution'), ('REFUND', 'Refund'), ('REVERSAL', 'Processor Reversal'), ('ADJUSTMENT', 'Filing Adjustment')], default='CONTRIBUTION', max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUPERSEDED', 'Superseded'), ('MANUALLY_EXCLUDED', 'Manually Excluded')], default='ACTIVE', max_length=50)),
                ('transaction_date', models.DateField()),
                ('filed_date', models.DateField(blank=True, null=True)),
                ('raw_address', models.TextField(blank=True)),
                ('employer', models.CharField(blank=True, max_length=255)),
                ('occupation', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ContributionCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_name', models.CharField(max_length=255)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('confidence_level', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='LOW', max_length=50)),
                ('confidence_explanation', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContributorEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('ORGANIZATION', 'Organization'), ('JOINT', 'Joint / Ambiguous Contributor'), ('UNKNOWN', 'Unknown')], default='INDIVIDUAL', max_length=50)),
                ('display_name', models.CharField(max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('data_quality_flags', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='DatasetCoverageMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage_start_date', models.DateField()),
                ('coverage_end_date', models.DateField()),
                ('coverage_complete_through', models.DateField()),
                ('coverage_scope', models.CharField(default='SOS Statewide', max_length=255)),
                ('coverage_status', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('PARTIAL', 'Partial'), ('APPARENTLY_CONTINUOUS', 'Apparently Continuous'), ('CONFIRMED_COMPLETE', 'Confirmed Complete'), ('STALE', 'Stale'), ('MIXED_COVERAGE', 'Mixed Coverage')], default='UNKNOWN', max_length=50)),
                ('continuity_status', models.CharField(blank=True, max_length=100)),
                ('source_obtained_date', models.DateField()),
                ('coverage_confirmed_by', models.CharField(blank=True, max_length=150)),
                ('coverage_confirmation_date', models.DateField(blank=True, null=True)),
                ('coverage_notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FieldAssertion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('confidence', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=50)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('SUPERSEDED', 'Superseded'), ('PREFERRED', 'Preferred')], default='PREFERRED', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipRuleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('monthly_interval_min', models.IntegerField(default=20)),
                ('monthly_interval_max', models.IntegerField(default=40)),
                ('active_grace_period', models.IntegerField(default=60)),
                ('min_recurring_payments', models.IntegerField(default=2)),
                ('allowed_amount_variance', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('skip_payment_allowed', models.BooleanField(default=True)),
                ('refund_behavior', models.CharField(default='EXCLUDE_TIMELINE', max_length=100)),
                ('coverage_requirements', models.CharField(default='CONFIRMED_OR_CONTINUOUS', max_length=100)),
                ('effective_date', models.DateField()),
                ('created_by', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SourceRecordLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_model_name', models.CharField(max_length=100)),
                ('target_record_id', models.IntegerField()),
                ('source_model_name', models.CharField(max_length=100)),
                ('source_record_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('EMAIL', 'Email Address'), ('PHONE', 'Phone Number')], max_length=50)),
                ('value', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('CURRENT', 'Current'), ('HISTORICAL', 'Historical')], default='CURRENT', max_length=50)),
                ('contributor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_points', to='roster.contributioncluster')),
            ],
        ),
        migrations.CreateModel(
            name='ContributionClusterAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.CharField(default='AUTOMATED_RESOLVER', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='roster.contribution')),
                ('contribution_cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='roster.contributioncluster')),
            ],
        ),
        migrations.AddField(
            model_name='contributioncluster',
            name='contributor_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='roster.contributorentity'),
        ),
        migrations.CreateModel(
            name='ImportMappingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mapping_rules', models.JSONField(help_text='JSON mapping rules from CSV headers to normalized fields')),
                ('source_type', models.CharField(default='SOS_CONTRIBUTION', max_length=50)),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_hash', models.CharField(max_length=64, unique=True)),
                ('file_type', models.CharField(max_length=50)),
                ('import_date', models.DateTimeField(auto_now_add=True)),
                ('imported_by', models.CharField(max_length=150)),
                ('row_count', models.IntegerField(default=0)),
                ('successful_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('duplicate_rows', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VALIDATING', 'Validating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('ROLLED_BACK', 'Rolled Back'), ('RESTORING', 'Restoring')], default='PENDING', max_length=50)),
                ('mapping_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roster.importmappingprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=20)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('precision_level', models.CharField(choices=[('STREET', 'Full Street Address'), ('CITY_ZIP', 'City and ZIP Locality'), ('ZIP_ONLY', 'ZIP Only'), ('INFERRED_COUNTY', 'County Inferred'), ('VOTER_CONFIRMED', 'Voter Confirmed Address'), ('MANUAL', 'Manually Assigned Geography')], max_length=50)),
                ('confidence', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=50)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CURRENT', 'Current'), ('HISTORICAL', 'Historical')], default='CURRENT', max_length=50)),
                ('is_observed', models.BooleanField(default=True)),
                ('is_inferred', models.BooleanField(default=False)),
                ('is_manual', models.BooleanField(default=False)),
                ('contributor_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='roster.contributioncluster')),
            ],
        ),
        migrations.CreateModel(
            name='MatchDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_record_id', models.IntegerField()),
                ('decision', models.CharField(choices=[('MATCHED', 'Matched'), ('REJECTED', 'Rejected')], default='MATCHED', max_length=50)),
                ('confidence', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('contribution_cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_decisions', to='roster.contributioncluster')),
            ],
        ),
        migrations.CreateModel(
            name='MembershipAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated_status', models.CharField(choices=[('ACTIVE', 'Active Member'), ('PROVISIONAL', 'New or Provisional Member'), ('LIKELY', 'Likely Member'), ('PREVIOUSLY_RECURRING', 'Previously Recurring'), ('LAPSED', 'Lapsed Member'), ('ONE_TIME', 'One-Time Donor'), ('UNKNOWN', 'Unknown'), ('INSUFFICIENT_HISTORY', 'Insufficient History'), ('DATASET_TOO_STALE', 'Dataset Too Stale')], max_length=100)),
                ('recurring_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payment_interval', models.CharField(blank=True, max_length=50)),
                ('calculation_date', models.DateTimeField(auto_now=True)),
                ('manual_override', models.BooleanField(default=False)),
                ('explanation', models.TextField(blank=True)),
                ('contributor_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_assessments', to='roster.contributorentity')),
                ('rule_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='roster.membershipruleversion')),
            ],
        ),
        migrations.CreateModel(
            name='MergeDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merge_date', models.DateTimeField(auto_now_add=True)),
                ('merged_by', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('source_cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merged_out_decisions', to='roster.contributioncluster')),
                ('target_cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merged_in_decisions', to='roster.contributioncluster')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=255)),
                ('committee_id', models.CharField(blank=True, max_length=100)),
                ('contributor_entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization_profile', to='roster.contributorentity')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=50)),
                ('contributor_entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person_profile', to='roster.contributorentity')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePatternAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated_pattern', models.CharField(choices=[('POSSIBLE_RECURRING', 'Possible Recurring Pattern'), ('SINGLE_VISIBLE_CONTRIBUTION', 'Single Visible Contribution'), ('PREVIOUSLY_RECURRING', 'Previously Recurring Pattern'), ('INSUFFICIENT_HISTORY', 'Insufficient History'), ('AMBIGUOUS_IDENTITY_CLUSTER', 'Ambiguous Identity Cluster')], max_length=100)),
                ('pattern_explanation', models.TextField(blank=True)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('contribution_cluster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pattern_assessment', to='roster.contributioncluster')),
            ],
        ),
        migrations.CreateModel(
            name='RawContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('original_values', models.JSONField(help_text='Raw values dict parsed from the CSV row')),
                ('raw_row_hash', models.CharField(max_length=64)),
                ('validation_status', models.CharField(choices=[('UNPROCESSED', 'Unprocessed'), ('ACCEPTED', 'Accepted'), ('EXACT_DUPLICATE', 'Exact Duplicate'), ('POSSIBLE_DUPLICATE', 'Possible Duplicate'), ('POSSIBLE_AMENDMENT', 'Possible Amendment'), ('VALIDATION_WARNING', 'Validation Warning'), ('VALIDATION_FAILURE', 'Validation Failure'), ('MANUALLY_EXCLUDED', 'Manually Excluded')], default='UNPROCESSED', max_length=50)),
                ('validation_errors', models.TextField(blank=True, null=True)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_contributions', to='roster.importbatch')),
            ],
        ),
        migrations.AddField(
            model_name='contribution',
            name='raw_contribution',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_contribution', to='roster.rawcontribution'),
        ),
    ]
