# Generated by Django 5.0.14 on 2026-07-27 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('attempted_by', models.CharField(max_length=150)),
                ('action', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='contributorentity',
            options={'permissions': [('view_sensitive_roster', 'Can view sensitive roster information'), ('import_contributions', 'Can upload and import contribution files'), ('override_duplicate_file', 'Can override duplicate file import blocks'), ('rollback_import', 'Can roll back imports'), ('restore_import', 'Can restore rolled-back imports'), ('manage_identity', 'Can merge, split, and correct contributor types'), ('override_membership', 'Can manually override membership status'), ('view_audit', 'Can view audit provenance records'), ('export_sensitive_data', 'Can export sensitive roster data'), ('purge_data', 'Can permanently purge data from CLI')]},
        ),
        migrations.AlterField(
            model_name='contribution',
            name='transaction_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='transaction_number',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contributioncluster',
            name='normalized_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contributioncluster',
            name='zip_code',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='contributionclusterassignment',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VALIDATING', 'Validating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('ROLLED_BACK', 'Rolled Back'), ('RESTORING', 'Restoring')], db_index=True, default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='rawcontribution',
            name='raw_row_hash',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['transaction_number', 'transaction_date'], name='idx_contrib_num_date'),
        ),
        migrations.AddIndex(
            model_name='contributioncluster',
            index=models.Index(fields=['normalized_name', 'zip_code'], name='idx_cluster_name_zip'),
        ),
        migrations.AddIndex(
            model_name='contributionclusterassignment',
            index=models.Index(fields=['contribution_cluster', 'is_active'], name='idx_assign_cluster_active'),
        ),
        migrations.AddIndex(
            model_name='rawcontribution',
            index=models.Index(fields=['import_batch', 'validation_status'], name='idx_raw_batch_status'),
        ),
        migrations.AddConstraint(
            model_name='contributionclusterassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('contribution',), name='unique_active_cluster_assignment_per_contribution'),
        ),
        migrations.AddField(
            model_name='importattempt',
            name='import_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='roster.importbatch'),
        ),
    ]
