# Generated by Django 5.0.14 on 2026-07-28 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0004_geographyresolutionrun_dataset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('state_code', models.CharField(default='CA', max_length=2)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=50)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('retired_date', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChapterEntityOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override_type', models.CharField(choices=[('INCLUDE', 'Include'), ('EXCLUDE', 'Exclude')], max_length=50)),
                ('reason', models.TextField()),
                ('effective_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('SUPERSEDED', 'Superseded'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=50)),
                ('created_by', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='roster.chapter')),
                ('contributor_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_overrides', to='roster.contributorentity')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='roster.chapterentityoverride')),
            ],
        ),
        migrations.CreateModel(
            name='ChapterEvaluationLocationSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection_status', models.CharField(choices=[('SELECTED', 'Selected'), ('MULTIPLE_EQUIVALENT', 'Multiple Equivalent'), ('AMBIGUOUS_LOCATION', 'Ambiguous Location'), ('NO_CURRENT_LOCATION', 'No Current Location'), ('NO_CURRENT_RESOLVED_LOCATION', 'No Current Resolved Location'), ('INELIGIBLE_ENTITY_TYPE', 'Ineligible Entity Type'), ('MANUALLY_SELECTED', 'Manually Selected')], max_length=50)),
                ('selection_method', models.CharField(choices=[('AUTOMATIC', 'Automatic'), ('MANUAL', 'Manual')], default='AUTOMATIC', max_length=50)),
                ('explanation', models.TextField(blank=True)),
                ('manual_selection', models.BooleanField(default=False)),
                ('actor', models.CharField(blank=True, max_length=150, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('contributor_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_location_selections', to='roster.contributorentity')),
                ('selected_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roster.location')),
                ('selected_resolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roster.locationgeographyresolution')),
            ],
        ),
        migrations.CreateModel(
            name='ChapterEvaluationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_mode', models.CharField(choices=[('PREVIEW', 'Preview'), ('APPLY', 'Apply')], max_length=50)),
                ('trigger_type', models.CharField(choices=[('RULE_SET_ACTIVATION', 'Rule Set Activation'), ('MANUAL_FULL_EVALUATION', 'Manual Full Evaluation'), ('GEOGRAPHY_RESOLUTION_UPDATE', 'Geography Resolution Update'), ('ENTITY_REEVALUATION', 'Entity Re-evaluation'), ('OVERRIDE_CHANGE', 'Override Change')], max_length=50)),
                ('geography_dataset_snapshot', models.JSONField()),
                ('resolver_version', models.CharField(max_length=50)),
                ('evaluation_engine_version', models.CharField(max_length=50)),
                ('membership_snapshot_date', models.DateField()),
                ('scope', models.CharField(max_length=255)),
                ('actor', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('SUPERSEDED', 'Superseded')], default='PENDING', max_length=50)),
                ('entities_considered', models.IntegerField(default=0)),
                ('included_count', models.IntegerField(default=0)),
                ('excluded_count', models.IntegerField(default=0)),
                ('ambiguous_count', models.IntegerField(default=0)),
                ('unresolved_count', models.IntegerField(default=0)),
                ('overlap_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('started_time', models.DateTimeField(blank=True, null=True)),
                ('completed_time', models.DateTimeField(blank=True, null=True)),
                ('error_summary', models.TextField(blank=True, null=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_runs', to='roster.chapter')),
                ('retry_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='roster.chapterevaluationrun')),
            ],
        ),
        migrations.CreateModel(
            name='ChapterEvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_status', models.CharField(choices=[('INCLUDED_BY_RULE', 'Included by Rule'), ('EXCLUDED_BY_RULE', 'Excluded by Rule'), ('MANUALLY_INCLUDED', 'Manually Included'), ('MANUALLY_EXCLUDED', 'Manually Excluded'), ('PROVISIONAL_GEOGRAPHIC_MATCH', 'Provisional Geographic Match'), ('AMBIGUOUS_GEOGRAPHY', 'Ambiguous Geography'), ('AMBIGUOUS_LOCATION', 'Ambiguous Location'), ('NO_CURRENT_LOCATION', 'No Current Location'), ('NO_CURRENT_RESOLVED_LOCATION', 'No Current Resolved Location'), ('NO_RULE_MATCH', 'No Rule Match'), ('INELIGIBLE_ENTITY_TYPE', 'Ineligible Entity Type'), ('ERROR', 'Error')], max_length=50)),
                ('confidence', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=50)),
                ('explanation', models.TextField(blank=True)),
                ('entity_type_snapshot', models.CharField(max_length=50)),
                ('entity_verification_snapshot', models.BooleanField()),
                ('membership_status_snapshot', models.CharField(max_length=50)),
                ('membership_rule_version_snapshot', models.CharField(max_length=50)),
                ('membership_assessment_date_snapshot', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='roster.chapter')),
                ('contributor_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_results', to='roster.contributorentity')),
                ('location_selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='roster.chapterevaluationlocationselection')),
                ('manual_override', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roster.chapterentityoverride')),
                ('membership_assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chapter_results', to='roster.membershipassessment')),
                ('selected_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roster.location')),
                ('selected_resolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roster.locationgeographyresolution')),
                ('evaluation_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='roster.chapterevaluationrun')),
            ],
        ),
        migrations.AddField(
            model_name='chapterevaluationlocationselection',
            name='evaluation_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_selections', to='roster.chapterevaluationrun'),
        ),
        migrations.CreateModel(
            name='ChapterAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_status', models.CharField(choices=[('INCLUDED', 'Included'), ('PROVISIONALLY_INCLUDED', 'Provisionally Included'), ('EXCLUDED', 'Excluded'), ('AMBIGUOUS', 'Ambiguous'), ('UNRESOLVED', 'Unresolved'), ('NO_MATCH', 'No Match'), ('INELIGIBLE', 'Ineligible')], max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='roster.chapter')),
                ('contributor_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_assignments', to='roster.contributorentity')),
                ('evaluation_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='roster.chapterevaluationresult')),
                ('evaluation_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='roster.chapterevaluationrun')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='current_evaluation_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='roster.chapterevaluationrun'),
        ),
        migrations.CreateModel(
            name='ChapterRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect', models.CharField(choices=[('INCLUDE', 'Include'), ('EXCLUDE', 'Exclude')], max_length=50)),
                ('target_type', models.CharField(choices=[('COUNTY', 'County'), ('PLACE', 'Place'), ('POSTAL_AREA', 'Postal Area')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roster.county')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roster.geographicplace')),
                ('postal_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roster.postalarea')),
            ],
        ),
        migrations.CreateModel(
            name='ChapterRuleMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_outcome', models.CharField(choices=[('MATCHED_INCLUDE', 'Matched Include'), ('MATCHED_EXCLUDE', 'Matched Exclude'), ('NOT_MATCHED', 'Not Matched'), ('NOT_EVALUATED', 'Not Evaluated'), ('AMBIGUOUS', 'Ambiguous')], max_length=50)),
                ('explanation', models.TextField(blank=True)),
                ('confidence', models.CharField(max_length=50)),
                ('evaluation_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_matches', to='roster.chapterevaluationresult')),
                ('location_resolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roster.locationgeographyresolution')),
                ('matched_county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roster.county')),
                ('matched_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roster.geographicplace')),
                ('matched_postal_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roster.postalarea')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='roster.chapterrule')),
            ],
        ),
        migrations.CreateModel(
            name='ChapterRuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('VALIDATING', 'Validating'), ('ACTIVE', 'Active'), ('SUPERSEDED', 'Superseded'), ('RETIRED', 'Retired'), ('INVALID', 'Invalid')], default='DRAFT', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('include_match_mode', models.CharField(default='ANY', max_length=50)),
                ('created_by', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_by', models.CharField(blank=True, max_length=150, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('validation_summary', models.TextField(blank=True, null=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_sets', to='roster.chapter')),
            ],
        ),
        migrations.AddField(
            model_name='chapterrule',
            name='rule_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='roster.chapterruleset'),
        ),
        migrations.AddField(
            model_name='chapterevaluationrun',
            name='rule_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_runs', to='roster.chapterruleset'),
        ),
        migrations.AddField(
            model_name='chapterevaluationresult',
            name='rule_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='roster.chapterruleset'),
        ),
        migrations.AddConstraint(
            model_name='chapterentityoverride',
            constraint=models.CheckConstraint(check=models.Q(('expiration_date__isnull', True), ('expiration_date__gte', models.F('effective_date')), _connector='OR'), name='check_override_expiration'),
        ),
        migrations.AddConstraint(
            model_name='chapterentityoverride',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('chapter', 'contributor_entity'), name='unique_active_override_per_chapter_and_entity'),
        ),
        migrations.AddConstraint(
            model_name='chapterassignment',
            constraint=models.UniqueConstraint(fields=('evaluation_run', 'contributor_entity'), name='unique_assignment_per_run_and_entity'),
        ),
        migrations.AddConstraint(
            model_name='chapterrulematch',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('matched_county__isnull', True), ('matched_place__isnull', True), ('matched_postal_area__isnull', True)), models.Q(('matched_county__isnull', False), ('matched_place__isnull', True), ('matched_postal_area__isnull', True)), models.Q(('matched_county__isnull', True), ('matched_place__isnull', False), ('matched_postal_area__isnull', True)), models.Q(('matched_county__isnull', True), ('matched_place__isnull', True), ('matched_postal_area__isnull', False)), _connector='OR'), name='check_match_target_mutually_exclusive'),
        ),
        migrations.AddConstraint(
            model_name='chapterruleset',
            constraint=models.UniqueConstraint(fields=('chapter', 'version'), name='unique_ruleset_version_per_chapter'),
        ),
        migrations.AddConstraint(
            model_name='chapterruleset',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('chapter',), name='unique_active_ruleset_per_chapter'),
        ),
        migrations.AddConstraint(
            model_name='chapterrule',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('county__isnull', False), ('place__isnull', True), ('postal_area__isnull', True)), models.Q(('county__isnull', True), ('place__isnull', False), ('postal_area__isnull', True)), models.Q(('county__isnull', True), ('place__isnull', True), ('postal_area__isnull', False)), _connector='OR'), name='check_target_mutually_exclusive'),
        ),
        migrations.AddConstraint(
            model_name='chapterrule',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('target_type', 'COUNTY'), _negated=True), models.Q(('county__isnull', False), ('place__isnull', True), ('postal_area__isnull', True)), _connector='OR'), name='check_target_type_county'),
        ),
        migrations.AddConstraint(
            model_name='chapterrule',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('target_type', 'PLACE'), _negated=True), models.Q(('county__isnull', True), ('place__isnull', False), ('postal_area__isnull', True)), _connector='OR'), name='check_target_type_place'),
        ),
        migrations.AddConstraint(
            model_name='chapterrule',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('target_type', 'POSTAL_AREA'), _negated=True), models.Q(('county__isnull', True), ('place__isnull', True), ('postal_area__isnull', False)), _connector='OR'), name='check_target_type_postal'),
        ),
        migrations.AddConstraint(
            model_name='chapterrule',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('target_type', 'COUNTY')), fields=('rule_set', 'effect', 'county'), name='unique_active_county_rule'),
        ),
        migrations.AddConstraint(
            model_name='chapterrule',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('target_type', 'PLACE')), fields=('rule_set', 'effect', 'place'), name='unique_active_place_rule'),
        ),
        migrations.AddConstraint(
            model_name='chapterrule',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('target_type', 'POSTAL_AREA')), fields=('rule_set', 'effect', 'postal_area'), name='unique_active_postal_rule'),
        ),
        migrations.AddConstraint(
            model_name='chapterevaluationrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('chapter', 'rule_set', 'run_mode', 'scope'), name='unique_pending_run_proposal'),
        ),
        migrations.AddConstraint(
            model_name='chapterevaluationresult',
            constraint=models.UniqueConstraint(fields=('evaluation_run', 'contributor_entity'), name='unique_result_per_run_and_entity'),
        ),
    ]
