# Generated by Django 5.0.14 on 2026-07-28 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0005_chapter_chapterentityoverride_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contributorentity',
            options={'permissions': [('view_sensitive_roster', 'Can view sensitive roster information'), ('import_contributions', 'Can upload and import contribution files'), ('override_duplicate_file', 'Can override duplicate file import blocks'), ('rollback_import', 'Can roll back imports'), ('restore_import', 'Can restore rolled-back imports'), ('manage_identity', 'Can merge, split, and correct contributor types'), ('override_membership', 'Can manually override membership status'), ('view_audit', 'Can view audit provenance records'), ('export_sensitive_data', 'Can export sensitive roster data'), ('purge_data', 'Can permanently purge data from CLI'), ('view_geography_reference', 'Can view reference geography maps and lists'), ('import_geography_reference', 'Can import geographic reference datasets'), ('manage_geography_reference', 'Can manage and activate geographic references'), ('rollback_geography_import', 'Can roll back and restore geographic imports'), ('resolve_geography_ambiguity', 'Can resolve ambiguous or conflicting contributor locations'), ('view_chapter_definitions', 'Can view chapter definitions'), ('manage_chapter_definitions', 'Can manage chapter definitions'), ('preview_chapter_rules', 'Can run previews of chapter rules'), ('activate_chapter_rules', 'Can activate chapter rule sets'), ('evaluate_chapter_rules', 'Can run apply evaluations for chapters'), ('manage_chapter_overrides', 'Can manage manual chapter overrides'), ('view_chapter_assignments', 'Can view contributor chapter assignments')]},
        ),
    ]
