# Generated by Django 5.0.14 on 2026-07-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0006_alter_contributorentity_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importbatch',
            name='file_hash',
            field=models.CharField(max_length=64),
        ),
    ]
