# Generated by Django 5.0.14 on 2026-07-28 02:11

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Max

def set_historical_assessments_not_current(apps, schema_editor):
    MembershipAssessment = apps.get_model('roster', 'MembershipAssessment')
    latest_ids = set(MembershipAssessment.objects.values('contributor_entity_id').annotate(max_id=Max('id')).values_list('max_id', flat=True))
    MembershipAssessment.objects.exclude(id__in=latest_ids).update(is_current=False)

class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0007_alter_importbatch_file_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributorentity',
            name='verification_evidence',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='contributorentity',
            name='verification_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contributorentity',
            name='verification_method',
            field=models.CharField(choices=[('NONE', 'None'), ('ADMIN_REVIEW', 'Administrative Review'), ('EXTERNAL_IDENTITY_MATCH', 'External Identity Match'), ('LEGACY_REVIEWED', 'Legacy Reviewed')], default='NONE', max_length=50),
        ),
        migrations.AddField(
            model_name='contributorentity',
            name='verification_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified')], default='UNVERIFIED', max_length=50),
        ),
        migrations.AddField(
            model_name='contributorentity',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contributorentity',
            name='verified_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='membershipassessment',
            name='identity_verified_at_assessment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membershipassessment',
            name='is_current',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.RunPython(
            code=set_historical_assessments_not_current,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='membershipassessment',
            name='membership_authority',
            field=models.CharField(choices=[('AUTHORITATIVE', 'Authoritative'), ('PROVISIONAL', 'Provisional'), ('INELIGIBLE', 'Ineligible')], default='PROVISIONAL', max_length=50),
        ),
        migrations.AddField(
            model_name='membershipassessment',
            name='recurrence_pattern_status',
            field=models.CharField(choices=[('RECURRING_PATTERN', 'Recurring Pattern'), ('PREVIOUSLY_RECURRING_PATTERN', 'Previously Recurring Pattern'), ('IRREGULAR_PATTERN', 'Irregular Pattern'), ('INSUFFICIENT_HISTORY', 'Insufficient History'), ('NO_RECURRING_PATTERN', 'No Recurring Pattern')], default='INSUFFICIENT_HISTORY', max_length=50),
        ),
        migrations.AddField(
            model_name='membershipassessment',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='roster.membershipassessment'),
        ),
        migrations.AddConstraint(
            model_name='contributorentity',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('verification_status', 'UNVERIFIED'), _negated=True), ('verification_method', 'NONE'), _connector='OR'), name='check_unverified_method_none'),
        ),
        migrations.AddConstraint(
            model_name='contributorentity',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('verification_status', 'VERIFIED'), _negated=True), models.Q(('verification_method', 'NONE'), _negated=True), _connector='OR'), name='check_verified_method_not_none'),
        ),
        migrations.AddConstraint(
            model_name='contributorentity',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('verification_status', 'VERIFIED'), _negated=True), ('verified_at__isnull', False), _connector='OR'), name='check_verified_has_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='contributorentity',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('verification_method', 'ADMIN_REVIEW'), _negated=True), ('verified_by__isnull', False), _connector='OR'), name='check_admin_verified_has_actor'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'COMPLETED')), fields=('file_hash',), name='unique_completed_batch_file_hash'),
        ),
        migrations.AddConstraint(
            model_name='membershipassessment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('contributor_entity',), name='unique_current_assessment_per_entity'),
        ),
    ]
