# Generated by Django 5.0.14 on 2026-07-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0008_contributorentity_verification_evidence_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contributorentity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_verified', True), ('verification_status', 'VERIFIED')), models.Q(('is_verified', False), ('verification_status', 'UNVERIFIED')), _connector='OR'), name='check_is_verified_sync'),
        ),
    ]
