# Generated by Django 6.0.6 on 2026-07-28 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0009_contributorentity_check_is_verified_sync'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmendmentRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('AMENDMENT', 'Amendment'), ('CORRECTION', 'Correction'), ('SUPERSESSION', 'Supersession')], max_length=50)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50)),
                ('financial_disposition', models.CharField(choices=[('ORIGINAL', 'Original is operative'), ('REPLACEMENT', 'Replacement is operative'), ('NEITHER', 'Neither is operative')], default='ORIGINAL', max_length=50)),
                ('recurrence_disposition', models.CharField(choices=[('ORIGINAL', 'Original is operative'), ('REPLACEMENT', 'Replacement is operative'), ('NEITHER', 'Neither is operative')], default='ORIGINAL', max_length=50)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True)),
                ('audit_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roster.auditevent')),
                ('operative_contribution', models.ForeignKey(blank=True, help_text='Which contribution is currently operative for totals', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='amendment_operative_for', to='roster.contribution')),
                ('original_contribution', models.ForeignKey(help_text='The original contribution being amended', on_delete=django.db.models.deletion.PROTECT, related_name='amendment_as_original', to='roster.contribution')),
                ('replacement_contribution', models.ForeignKey(help_text='The replacement contribution', on_delete=django.db.models.deletion.PROTECT, related_name='amendment_as_replacement', to='roster.contribution')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('original_contribution', models.F('replacement_contribution')), _negated=True), name='amendment_not_self_referential'), models.UniqueConstraint(fields=('original_contribution', 'replacement_contribution'), name='unique_amendment_pair')],
            },
        ),
    ]
