# Generated by Django 6.0.6 on 2026-07-28 17:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0010_amendment_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='amendmentrelationship',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amendmentrelationship',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
